export const GET_TESTS = "GET_TESTS"
export const GET_TESTPROPERTIES = "GET_TESTPROPERTIES"
export const LOGIN_PATIENT = "LOGIN_PATIENT"
export const LOGIN_LABORANT = "LOGIN_LABORANT"
export const GET_PATIENT_TESTS = "GET_PATIENT_TESTS"
export const GET_PATIENT_TESTS_PROPERTIES = "GET_PATIENT_TESTS_PROPERTIES"
export const SET_SELECTED_PATIENT_TEST = "SET_SELECTED_PATIENT_TEST"
export const SET_SELECTED_TEST = "SET_SELECTED_TEST"
export const GET_PATIENTS = "GET_PATIENTS"
export const LOGOUT="LOGOUT"



